### ISSUE TITLE
consider renaming library

### ISSUE THREAD

**Issue by s3rj1k** [dohnto/pydor#5]
current library name is not the best name for a software. 
in Russian this means, homosexual in a bad way.
also this name variants are not acceptable:

- pydr 
- pdr
- pdor

**Comment by dohnto** [comment]
The name is an abbreviation of `PYthon Docker Registry`.

Are you using this library and you are offended or are you just a passing by? I am sorry but I am not sure whether if I rename it won't be  offensive in some other language which I don't know.

If you cannot overcome my naming, consider using [docker-registry-client](https://github.com/yodle/docker-registry-client) which might be less offensive for you.

**Comment by s3rj1k** [comment]
@dohnto Hi, not offended. Just wanted to let you know about translation.
You could add abbreviation disambiguation to main readme, for future references.

**Comment by dohnto** [comment]
Thank you. It was a poor choice, but I am not going to change it since it is not maintained actively anymore.
